"""platform schema

Revision ID: c5333aa811a5
Revises:
Create Date: 2026-09-06 07:14:31.484883+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c5333aa811a5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "entity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("functional_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "code", name="uq_entity_org_code"),
    )
    op.create_index(op.f("ix_entity_org_id"), "entity", ["org_id"], unique=False)
    op.create_table(
        "membership",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_membership_org_user"),
    )
    op.create_index(op.f("ix_membership_org_id"), "membership", ["org_id"], unique=False)
    op.create_index(op.f("ix_membership_user_id"), "membership", ["user_id"], unique=False)
    op.create_table(
        "policy_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("set_by", sa.String(length=255), nullable=False),
        sa.Column(
            "set_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("set_by LIKE 'human:%%'", name="ck_policy_version_set_by_is_human"),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "version", name="uq_policy_version_org_version"),
    )
    op.create_index(op.f("ix_policy_version_org_id"), "policy_version", ["org_id"], unique=False)
    op.create_table(
        "upload",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("stored_path", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("quarantined_row_count", sa.Integer(), nullable=False),
        sa.Column("quarantine_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uploaded_by", sa.String(length=255), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("byte_size >= 0", name="ck_upload_byte_size_nonneg"),
        sa.CheckConstraint("quarantined_row_count >= 0", name="ck_upload_quarantined_nonneg"),
        sa.CheckConstraint("row_count >= 0", name="ck_upload_row_count_nonneg"),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_upload_org_id"), "upload", ["org_id"], unique=False)
    op.create_index("ix_upload_org_sha256", "upload", ["org_id", "sha256"], unique=False)
    op.create_table(
        "run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version_label", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                name="run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("manifest_ref", sa.String(length=255), nullable=True),
        sa.Column("event_log_path", sa.String(length=1024), nullable=True),
        sa.Column("event_log_head_hash", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="ck_run_progress_range"),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["policy_version_id"], ["policy_version.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_org_id"), "run", ["org_id"], unique=False)
    op.create_index("ix_run_org_period", "run", ["org_id", "period"], unique=False)
    op.create_index("ix_run_org_status", "run", ["org_id", "status"], unique=False)
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("attempts >= 0", name="ck_job_attempts_nonneg"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_job_max_attempts_positive"),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="ck_job_progress_range"),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_claim", "job", ["status", "available_at", "created_at"], unique=False)
    op.create_index(op.f("ix_job_org_id"), "job", ["org_id"], unique=False)
    op.create_index("ix_job_org_status", "job", ["org_id", "status"], unique=False)
    op.create_table(
        "prior_decision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column(
            "outcome_class",
            sa.Enum(
                "MATCHED",
                "REFUND_MATCHED",
                "PARTIAL_REFUND",
                "LATE_SETTLEMENT",
                "AMOUNT_MISMATCH",
                "FEE_MISMATCH",
                "CURRENCY_MISMATCH",
                "MISSING_PROCESSOR",
                "MISSING_INTERNAL",
                "MISSING_BANK_SETTLEMENT",
                "AMBIGUOUS_MATCH",
                name="outcome_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount_delta", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "human_verdict",
            sa.Enum(
                "approved",
                "rejected",
                "reclassified",
                name="human_verdict",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_work_key", sa.String(length=255), nullable=True),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("decided_by LIKE 'human:%%'", name="ck_prior_decision_human_only"),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_run_id"], ["run.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prior_decision_org_id"), "prior_decision", ["org_id"], unique=False)
    op.create_index(
        "ix_prior_decision_org_reason", "prior_decision", ["org_id", "reason_code"], unique=False
    )
    op.create_table(
        "work_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("work_key", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("ledger_count", sa.Integer(), nullable=False),
        sa.Column("processor_count", sa.Integer(), nullable=False),
        sa.Column("bank_count", sa.Integer(), nullable=False),
        sa.Column("source_row_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "work_key", name="uq_work_item_run_key"),
    )
    op.create_index("ix_work_item_org_amount", "work_item", ["org_id", "amount"], unique=False)
    op.create_index(op.f("ix_work_item_org_id"), "work_item", ["org_id"], unique=False)
    op.create_index("ix_work_item_org_run", "work_item", ["org_id", "run_id"], unique=False)
    op.create_table(
        "verdict",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("work_key", sa.String(length=255), nullable=False),
        sa.Column(
            "outcome_class",
            sa.Enum(
                "MATCHED",
                "REFUND_MATCHED",
                "PARTIAL_REFUND",
                "LATE_SETTLEMENT",
                "AMOUNT_MISMATCH",
                "FEE_MISMATCH",
                "CURRENCY_MISMATCH",
                "MISSING_PROCESSOR",
                "MISSING_INTERNAL",
                "MISSING_BANK_SETTLEMENT",
                "AMBIGUOUS_MATCH",
                name="outcome_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("amount_delta", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fee_explained_delta", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version_label", sa.String(length=64), nullable=False),
        sa.Column(
            "adjudicator",
            sa.Enum(
                "DETERMINISTIC",
                "LLM",
                "HUMAN",
                name="adjudicator",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("evidence_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_verdict_confidence_range"),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_item_id"], ["work_item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_item_id", name="uq_verdict_work_item"),
    )
    op.create_index(op.f("ix_verdict_org_id"), "verdict", ["org_id"], unique=False)
    op.create_index("ix_verdict_org_outcome", "verdict", ["org_id", "outcome_class"], unique=False)
    op.create_index("ix_verdict_org_reason", "verdict", ["org_id", "reason_code"], unique=False)
    op.create_table(
        "disposition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("verdict_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("T0", "T1", "T2", "T3", name="tier", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "AUTO_POST",
                "AUTO_SAMPLED",
                "ESCALATE",
                "REFUSE",
                name="disposition_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "review_state",
            sa.Enum(
                "open",
                "approved",
                "rejected",
                "reclassified",
                name="review_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reclassified_to",
            sa.Enum(
                "MATCHED",
                "REFUND_MATCHED",
                "PARTIAL_REFUND",
                "LATE_SETTLEMENT",
                "AMOUNT_MISMATCH",
                "FEE_MISMATCH",
                "CURRENCY_MISMATCH",
                "MISSING_PROCESSOR",
                "MISSING_INTERNAL",
                "MISSING_BANK_SETTLEMENT",
                "AMBIGUOUS_MATCH",
                name="outcome_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("cited_prior_decision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "action <> 'REFUSE' OR blocking IS TRUE", name="ck_disposition_refuse_is_blocking"
        ),
        sa.CheckConstraint(
            "reviewed_by IS NULL OR approved_by IS NULL OR reviewed_by <> approved_by",
            name="ck_disposition_four_eyes",
        ),
        sa.ForeignKeyConstraint(
            ["cited_prior_decision_id"], ["prior_decision.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["verdict_id"], ["verdict.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("verdict_id", name="uq_disposition_verdict"),
    )
    op.create_index("ix_disposition_org_action", "disposition", ["org_id", "action"], unique=False)
    op.create_index(op.f("ix_disposition_org_id"), "disposition", ["org_id"], unique=False)
    op.create_index(
        "ix_disposition_org_queue",
        "disposition",
        ["org_id", "review_state", "blocking"],
        unique=False,
    )
    op.create_index(op.f("ix_disposition_run_id"), "disposition", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_disposition_run_id"), table_name="disposition")
    op.drop_index("ix_disposition_org_queue", table_name="disposition")
    op.drop_index(op.f("ix_disposition_org_id"), table_name="disposition")
    op.drop_index("ix_disposition_org_action", table_name="disposition")
    op.drop_table("disposition")
    op.drop_index("ix_verdict_org_reason", table_name="verdict")
    op.drop_index("ix_verdict_org_outcome", table_name="verdict")
    op.drop_index(op.f("ix_verdict_org_id"), table_name="verdict")
    op.drop_table("verdict")
    op.drop_index("ix_work_item_org_run", table_name="work_item")
    op.drop_index(op.f("ix_work_item_org_id"), table_name="work_item")
    op.drop_index("ix_work_item_org_amount", table_name="work_item")
    op.drop_table("work_item")
    op.drop_index("ix_prior_decision_org_reason", table_name="prior_decision")
    op.drop_index(op.f("ix_prior_decision_org_id"), table_name="prior_decision")
    op.drop_table("prior_decision")
    op.drop_index("ix_job_org_status", table_name="job")
    op.drop_index(op.f("ix_job_org_id"), table_name="job")
    op.drop_index("ix_job_claim", table_name="job")
    op.drop_table("job")
    op.drop_index("ix_run_org_status", table_name="run")
    op.drop_index("ix_run_org_period", table_name="run")
    op.drop_index(op.f("ix_run_org_id"), table_name="run")
    op.drop_table("run")
    op.drop_index("ix_upload_org_sha256", table_name="upload")
    op.drop_index(op.f("ix_upload_org_id"), table_name="upload")
    op.drop_table("upload")
    op.drop_index(op.f("ix_policy_version_org_id"), table_name="policy_version")
    op.drop_table("policy_version")
    op.drop_index(op.f("ix_membership_user_id"), table_name="membership")
    op.drop_index(op.f("ix_membership_org_id"), table_name="membership")
    op.drop_table("membership")
    op.drop_index(op.f("ix_entity_org_id"), table_name="entity")
    op.drop_table("entity")
    op.drop_table("organisation")
    # ### end Alembic commands ###
